=== koradgy/ZF440N_XMLGyak/ZF440N_1011/ZF440N_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
     <!--tanev, egyetem, id, jovahagyas tipus-->
     <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:string">

        </xs:restriction>
     </xs:simpleType>
     <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="ME"/>
        </xs:restriction>
     </xs:simpleType>

     <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:minLength value="5"/>
            <xs:maxLength value="10"/>
        </xs:restriction>
     </xs:simpleType>

    <xs:element name="hallgato" type="hallgatoTipus" />
    <xs:element name="kurzusok">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzus" type="kurzusTipus" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ZF440N_kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato" />
                <xs:element ref="kurzusok"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="hallgatoTipus">
        <xs:sequence>
            <xs:element name="hnev" type="xs:string" />
            <xs:element name="szulev" type="xs:string" />
            <xs:element name="szak" type="szakTipus" />
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="kurzusTipus">
        <xs:sequence>
            <xs:element name="kurzusnev" type="xs:string" />
            <xs:element name="kredit" type="xs:int" />
            <xs:element name="hely" type="xs:string" />
            <xs:element name="idopont" type="xs:string" />
            <xs:element name="oktato" type="xs:string" />
            <xs:element name="oraado" type="xs:string" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="szakTipus">
        <xs:sequence>
            
        </xs:sequence>
        <xs:attribute name="evf" type="xs:int"/>
    </xs:complexType>
</xs:schema>

=== koradgy/ZF440N_XMLGyak/ZF440N_1025/saxZF440N/ZF440N_kurzusfelvetel.xml
<ZF440N_kurzusfelvetel tanev="2023/24_I" egyetem="ME" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="ZF440N_kurzusfelvetel.xsd">

    <hallgato id="ZF440N.ME">
        <hnev>Kórád György</hnev>
        <szulev>2000-10-06</szulev>
        <szak evf="5"> Programtervező Informatikus </szak>
    </hallgato>
    <kurzusok>
        <kurzus id="GEIAL331-B" nyelv="magyar">
            <kurzusnev>WEB technológiák 1</kurzusnev>
            <kredit>5</kredit>
            <hely>A1 315</hely>
            <idopont>Hétfő 14:00-18:00</idopont>
            <oktato>Agárdi Anita</oktato>
        </kurzus>

        <kurzus id="GEMAK234-B" nyelv="magyar">
            <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
            <kredit>5</kredit>
            <hely>A1 320</hely>
            <idopont>Kedd 14:00-18:00</idopont>
            <oktato>Házy Attila</oktato>
        </kurzus>

        <kurzus id="GEMAK232-B" nyelv="magyar">
            <kurzusnev>Valószínűség-számítás</kurzusnev>
            <kredit>5</kredit>
            <hely>A1 320</hely>
            <idopont>Hétfő 10:00-12:00</idopont>
            <oktato>Dr. Fegyverneki Sándor</oktato>
        </kurzus>

        <kurzus id="GEIAK130-B" nyelv="magyar">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>A1 32.EA</hely>
            <idopont>Kedd 10:00-12:00</idopont>
            <oktato>Kunné Dr. Tamási Judit</oktato>
            <oraado>Fazekas Levente</oraado>
        </kurzus>

        <kurzus id="GEIAL332-B" nyelv="magyar">
            <kurzusnev>Adatkezelés XML-ben</kurzusnev>
            <kredit>5</kredit>
            <hely>A1 32.EA</hely>
            <idopont>Kedd 12:00-14:00</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>

    </kurzusok>
</ZF440N_kurzusfelvetel>
