=== koradgy/ZF440N_XMLGyak/XMLTaskZF440N/XMLSchemaZF440N.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Egyszerű típusok -->
    <xs:simpleType name="irszType">
        <xs:restriction base="xs:string">
            <xs:length value="4"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="evType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2023"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="hoType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="napType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="31"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="letszamType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tagozatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Matematika"/>
            <xs:enumeration value="Angol"/>
            <xs:enumeration value="Testnevelés"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="erdemjegyType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Összetett típusok -->

    <!-- TanarType -->
    <xs:complexType name="TanarType">
        <xs:sequence>
            <xs:element name="nev" type="nevTipus"/>
            <xs:element name="lakcim" type="lakcimTipus"/>
            <xs:element name="szulido" type="szulidoTipus"/>
            <xs:element name="telefonok" type="telefonokTipus"/>
        </xs:sequence>
        <xs:attribute name="tanarID" type="xs:integer" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="telefonokTipus">
        <xs:sequence>
            <xs:element name="telefon" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- TantargyType -->
    <xs:complexType name="TantargyType">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="targyID" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- TankonyvType -->
    <xs:complexType name="TankonyvType">
        <xs:sequence>
            <xs:element name="cim" type="xs:string"/>
            <xs:element name="iro" type="xs:string"/>
            <xs:element name="kiado" type="xs:string"/>
            <xs:element name="kiadido" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="TkonyvID" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- KonyvType -->
    <xs:complexType name="KonyvType">
        <xs:attribute name="konyvID" type="xs:integer" use="required"/>
        <xs:attribute name="TkonyvRef" type="xs:integer" use="required"/>
        <xs:attribute name="targyRef" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- TanuloType -->
    <xs:complexType name="TanuloType">
        <xs:attribute name="tanuloID" type="xs:integer" use="required"/>
        <xs:attribute name="osztalyRef" type="xs:integer" use="required"/>
        <xs:attribute name="diakRef" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- OsztalyfonokType -->
    <xs:complexType name="OsztalyfonokType">
        <xs:attribute name="ofID" type="xs:integer" use="required"/>
        <xs:attribute name="tanarRef" type="xs:integer" use="required"/>
        <xs:attribute name="osztalyRef" type="xs:integer" use="required"/>
    </xs:complexType>


    <!-- OsztalyType -->
    <xs:complexType name="OsztalyType">
        <xs:sequence>
            <xs:element name="letszam" type="letszamType"/>
            <xs:element name="tagozat" type="tagozatType"/>
        </xs:sequence>
        <xs:attribute name="osztalyID" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- TanitType -->
    <xs:complexType name="TanitType">
        <xs:sequence>
            <xs:element name="szint" type="xs:string"/>
            <xs:element name="miota" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="tanitID" type="xs:integer" use="required"/>
        <xs:attribute name="tanarRef" type="xs:integer" use="required"/>
        <xs:attribute name="targyRef" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- DiakType -->
    <xs:complexType name="DiakType">
        <xs:sequence>
            <xs:element name="nev" type="nevTipus"/>
            <xs:element name="lakcim" type="lakcimTipus"/>
            <xs:element name="szulido" type="szulidoTipus"/>
            <xs:element name="anyjaneve" type="xs:string"/>
            <xs:element name="kor" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="diakID" type="xs:integer" use="required"/>
    </xs:complexType>



    <!-- TanulType -->
    <xs:complexType name="TanulType">
        <xs:sequence>
            <xs:element name="erdemjegy" type="erdemjegyType"/>
            <xs:element name="datum" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="tanulID" type="xs:integer" use="required"/>
        <xs:attribute name="diakRef" type="xs:integer" use="required"/>
        <xs:attribute name="konyvRef" type="xs:integer" use="required"/>
    </xs:complexType>


    <!-- Szemelyes adatok -->
    <xs:complexType name="nevTipus">
        <xs:sequence>
            <xs:element name="vnev" type="xs:string"/>
            <xs:element name="knev" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="lakcimTipus">
        <xs:sequence>
            <xs:element name="irsz" type="irszType"/>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hsz" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="szulidoTipus">
        <xs:sequence>
            <xs:element name="ev" type="evType"/>
            <xs:element name="ho" type="hoType"/>
            <xs:element name="nap" type="napType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Gyökér elem -->
    <xs:element name="Iskola_ZF440N">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Tanar" type="TanarType" maxOccurs="unbounded"/>
                <xs:element name="Tanit" type="TanitType" maxOccurs="unbounded"/>
                <xs:element name="Diak" type="DiakType" maxOccurs="unbounded"/>
                <xs:element name="Tanul" type="TanulType" maxOccurs="unbounded"/>
                <xs:element name="Osztaly" type="OsztalyType" maxOccurs="unbounded"/>
                <xs:element name="Tanulo" type="TanuloType" maxOccurs="unbounded"/>
                <xs:element name="Osztalyfonok" type="OsztalyfonokType" maxOccurs="unbounded"/>
                <xs:element name="Tantargy" type="TantargyType" maxOccurs="unbounded"/>
                <xs:element name="Tankonyv" type="TankonyvType" maxOccurs="unbounded"/>
                <xs:element name="Konyv" type="KonyvType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>


        <!-- Elsődleges kulcsok-->
            <xs:key name="tanar_kulcs">
                    <xs:selector xpath="TanarType"/>
                    <xs:field xpath="@tanarID"/>
            </xs:key>

            <xs:key name="targy_kulcs">
                    <xs:selector xpath="TantargyType"/>
                    <xs:field xpath="@targyID"/>
            </xs:key>

            <xs:key name="tankonyv_kulcs">
                    <xs:selector xpath="TankonyvType"/>
                    <xs:field xpath="@TkonyvID"/>
            </xs:key>

            <xs:key name="konyv_kulcs">
                    <xs:selector xpath="KonyvType"/>
                    <xs:field xpath="@konyvID"/>
            </xs:key>

            <xs:key name="tan_kulcs">
                    <xs:selector xpath="TanuloType"/>
                    <xs:field xpath="@tanuloID"/>
            </xs:key>

            <xs:key name="ofi_kulcs">
                    <xs:selector xpath="OsztalyfonokType"/>
                    <xs:field xpath="@ofID"/>
            </xs:key>

            <xs:key name="osztaly">
                    <xs:selector xpath="OsztalyType"/>
                    <xs:field xpath="@osztalyID"/>
            </xs:key>

            <xs:key name="tanit_kulcs">
                    <xs:selector xpath="TanitType"/>
                    <xs:field xpath="@tanitID"/>
            </xs:key>

            <xs:key name="diak_kulcs">
                <xs:selector xpath="DiakType"/>
                <xs:field xpath="@diakID"/>
            </xs:key>

            <xs:key name="tanul_kulcs" >
                <xs:selector xpath="TanulType"/>
                <xs:field xpath="@tanulID"/>
            </xs:key>

            <!--Idegen kulcsok-->
            <xs:keyref name="tanar-tanit_kulcs" refer="tanar_kulcs">
                <xs:selector xpath="TanitType"/>
                <xs:field xpath="@tanarRef"/>
            </xs:keyref>
            
            <xs:keyref name="diak-tanul_kulcs" refer="diak_kulcs">
                <xs:selector xpath="TanulType"/>
                <xs:field xpath="@diakRef"/>
            </xs:keyref>
            
            <xs:keyref name="tanulo-osztaly_kulcs" refer="tan_kulcs">
                <xs:selector xpath="TanuloType"/>
                <xs:field xpath="@osztalyRef"/>
            </xs:keyref>
            
            <xs:keyref name="osztaly-osztalyfonok_kulcs" refer="ofi_kulcs">
                <xs:selector xpath="OsztalyfonokType"/>
                <xs:field xpath="@osztalyRef"/>
            </xs:keyref>
            
            <xs:keyref name="tanar-targy_kulcs" refer="tanit_kulcs">
                <xs:selector xpath="TanitType"/>
                <xs:field xpath="@targyRef"/>
            </xs:keyref>

            <xs:keyref name="diak-tanul" refer="diak_kulcs">
                <xs:selector xpath="TanulType"/>
                <xs:field xpath="@diakRef"/>
            </xs:keyref>

            <xs:keyref name="diak-osztay_kulcs" refer="diak_kulcs">
                <xs:selector xpath="TanuloType"/>
                <xs:field xpath="@diakRef"/>
            </xs:keyref>

            <xs:keyref name="tantargy-tankonyv_kulcs" refer="konyv_kulcs">
                <xs:selector xpath="KonyvType"/>
                <xs:field xpath="@targyRef"/>
            </xs:keyref>

            <!-- 1:1 kapcsolat-->

            <xs:unique name="osztaly-tanar_kapcsolat">
                <xs:selector xpath="TanarType"/>
                <xs:field xpath="tanarID"/>
            </xs:unique>
    </xs:element>
</xs:schema>

=== koradgy/ZF440N_XMLGyak/XMLTaskZF440N/DOMParseZF440N/XMLZF440N_output.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Iskola_ZF440N xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaZF440N.xsd">

  <Tanar>
    <nev>
      <vnev>Kovács</vnev>
      <knev>Anna</knev>
    </nev>
    <lakcim>
      <irsz>1024</irsz>
      <varos>Budapest</varos>
      <utca>Kossuth utca</utca>
      <hsz>5</hsz>
    </lakcim> 
    <szulido>
      <ev>1985</ev>
      <ho>3</ho>
      <nap>10</nap>
    </szulido>
    <telefon>123456789</telefon>    
  </Tanar>

  <Tanit>
    <szint>közép</szint>
    <miota>2015</miota>
  </Tanit>

  <Osztaly>
    <letszam>30</letszam>
    <tagozat>Matematika</tagozat>
  </Osztaly>

  <Tantargy>
    <nev>Magyar nyelv és irodalom</nev>
  </Tantargy>

  <Tankonyv>
    <cim>Az elveszett idő nyomában</cim>
    <iro>József Attila</iro>
    <kiado>Könyvkiadó Kft.</kiado>
    <kiadido>2022-09-01</kiadido>
  </Tankonyv>

  <Diak>
    <nev>
      <vnev>Péter</vnev>
      <knev>Nagy</knev>
    </nev>
    <lakcim>
      <irsz>1111</irsz>
      <varos>Szeged</varos>
      <utca>Petőfi utca</utca>
      <hsz>15</hsz>
    </lakcim> 
    <szulido>
      <ev>2005</ev>
      <ho>7</ho>
      <nap>5</nap>
    </szulido>
    <anyjaneve>Nagy Mária</anyjaneve>
    <kor>18</kor>    
  </Diak>

  <Tanul>
    <erdemjegy>4</erdemjegy>
    <datum>2023-11-15</datum>
  </Tanul>

 </Iskola_ZF440N>

=== koradgy/ZF440N_XMLGyak/XMLTaskZF440N/XMLZF440N1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Iskola_ZF440N xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaZF440N.xsd">


  <!--Tanárok-->

  <Tanar tanarID="1">
    <nev>
      <vnev>Kovács</vnev>
      <knev>Anna</knev>
    </nev>
    <lakcim>
      <irsz>1024</irsz>
      <varos>Budapest</varos>
      <utca>Kossuth utca</utca>
      <hsz>5</hsz>
    </lakcim> 
    <szulido>
      <ev>1985</ev>
      <ho>3</ho>
      <nap>10</nap>
    </szulido>
    <telefon>123456789</telefon>    
  </Tanar>

  <Tanit tanarRef="1" tanitID="1" targyRef="1">
    <szint>közép</szint>
    <miota>2015</miota>
  </Tanit>

  <Tanar tanarID="2">
    <nev>
      <vnev>Szabó</vnev>
      <knev>Péter</knev>
    </nev>
    <lakcim>
      <irsz>1132</irsz>
      <varos>Budapest</varos>
      <utca>Alkotás utca</utca>
      <hsz>12</hsz>
    </lakcim> 
    <szulido>
      <ev>1978</ev>
      <ho>6</ho>
      <nap>25</nap>
    </szulido>
    <telefon>987654321</telefon>    
  </Tanar>

  <Tanit tanarRef="2" tanitID="2" targyRef="2">
    <szint>alsó</szint>
    <miota>2010</miota>
  </Tanit>

  <Tanar tanarID="3">
    <nev>
      <vnev>Király</vnev>
      <knev>Mária</knev>
    </nev>
    <lakcim>
      <irsz>1098</irsz>
      <varos>Budapest</varos>
      <utca>Szent István utca</utca>
      <hsz>8</hsz>
    </lakcim> 
    <szulido>
      <ev>1990</ev>
      <ho>12</ho>
      <nap>15</nap>
    </szulido>
    <telefon>555444333</telefon>    
  </Tanar>

  <Tanit tanarRef="3" tanitID="3" targyRef="3">
    <szint>felső</szint>
    <miota>2012</miota>
  </Tanit>

  <Tanar tanarID="4">
    <nev>
      <vnev>Nagy</vnev>
      <knev>Gábor</knev>
    </nev>
    <lakcim>
      <irsz>1145</irsz>
      <varos>Budapest</varos>
      <utca>Kossuth Lajos utca</utca>
      <hsz>20</hsz>
    </lakcim> 
    <szulido>
      <ev>1982</ev>
      <ho>8</ho>
      <nap>5</nap>
    </szulido>
    <telefon>111222333</telefon>    
  </Tanar>

  <Tanit tanarRef="4" tanitID="4" targyRef="4">
    <szint>közép</szint>
    <miota>2018</miota>
  </Tanit>

  <Tanar tanarID="5">
    <nev>
      <vnev>Kiss</vnev>
      <knev>Éva</knev>
    </nev>
    <lakcim>
      <irsz>1066</irsz>
      <varos>Budapest</varos>
      <utca>Andrássy út</utca>
      <hsz>18</hsz>
    </lakcim> 
    <szulido>
      <ev>1988</ev>
      <ho>5</ho>
      <nap>20</nap>
    </szulido>
    <telefon>999888777</telefon>    
  </Tanar>

  <Tanit tanarRef="5" tanitID="5" targyRef="5">
    <szint>felső</szint>
    <miota>2016</miota>
  </Tanit>


  <!--Diákok-->

  <Diak diakID="1">  
    <nev>
      <vnev>Nagy</vnev>
      <knev>Péter</knev>
    </nev>
    <lakcim>
      <irsz>1111</irsz>
      <varos>Szeged</varos>
      <utca>Petőfi utca</utca>
      <hsz>15</hsz>
    </lakcim> 
    <szulido>
      <ev>2005</ev>
      <ho>7</ho>
      <nap>5</nap>
    </szulido>
    <anyjaneve>Nagy Mária</anyjaneve>
    <kor>18</kor>    
  </Diak>

  <Tanul diakRef="1" konyvRef="1" tanulID="1">
    <erdemjegy>4</erdemjegy>
    <datum>2023-11-15</datum>
  </Tanul>

  <Diak diakID="2">  
    <nev>
      <vnev>Kis</vnev>
      <knev>Anna</knev>
    </nev>
    <lakcim>
      <irsz>1020</irsz>
      <varos>Budapest</varos>
      <utca>Alkotmány utca</utca>
      <hsz>8</hsz>
    </lakcim> 
    <szulido>
      <ev>2004</ev>
      <ho>5</ho>
      <nap>12</nap>
    </szulido>
    <anyjaneve>Kis Zsuzsanna</anyjaneve>
    <kor>19</kor>    
  </Diak>

  <Tanul diakRef="2" konyvRef="2" tanulID="2">
    <erdemjegy>5</erdemjegy>
    <datum>2023-10-20</datum>
  </Tanul>

  <Diak diakID="3">  
    <nev>
      <vnev>Tóth</vnev>
      <knev>Géza</knev>
    </nev>
    <lakcim>
      <irsz>1138</irsz>
      <varos>Budapest</varos>
      <utca>Váci utca</utca>
      <hsz>10</hsz>
    </lakcim> 
    <szulido>
      <ev>2006</ev>
      <ho>8</ho>
      <nap>28</nap>
    </szulido>
    <anyjaneve>Tóth Éva</anyjaneve>
    <kor>17</kor>    
  </Diak>

  <Tanul diakRef="3" konyvRef="3" tanulID="3">
    <erdemjegy>3</erdemjegy>
    <datum>2023-11-05</datum>
  </Tanul>

  <Diak diakID="4">  
    <nev>
      <vnev>Nagy</vnev>
      <knev>Mária</knev>
    </nev>
    <lakcim>
      <irsz>1095</irsz>
      <varos>Budapest</varos>
      <utca>Kerepesi út</utca>
      <hsz>22</hsz>
    </lakcim> 
    <szulido>
      <ev>2003</ev>
      <ho>4</ho>
      <nap>15</nap>
    </szulido>
    <anyjaneve>Nagy Erzsébet</anyjaneve>
    <kor>19</kor>    
  </Diak>

  <Tanul diakRef="4" konyvRef="4" tanulID="4">
    <erdemjegy>5</erdemjegy>
    <datum>2023-10-10</datum>
  </Tanul>

  <!--Osztályok-->

  <Osztaly osztalyID="1">
    <letszam>30</letszam>
    <tagozat>Matematika</tagozat>
  </Osztaly>

  <Osztaly osztalyID="2">
    <letszam>24</letszam>
    <tagozat>Angol</tagozat>
  </Osztaly>

  <Osztaly osztalyID="3">
    <letszam>15</letszam>
    <tagozat>Testnevelés</tagozat>
  </Osztaly>

  <Tanulo diakRef="1" osztalyRef="1" tanuloID="1"> </Tanulo>
  <Tanulo diakRef="3" osztalyRef="1" tanuloID="2"> </Tanulo>
  <Tanulo diakRef="4" osztalyRef="2" tanuloID="3"> </Tanulo>
  <Tanulo diakRef="2" osztalyRef="3" tanuloID="4"> </Tanulo>

  <Osztalyfonok ofID="1" osztalyRef="1" tanarRef="2"/>
  <Osztalyfonok ofID="2" osztalyRef="3" tanarRef="2"/>
  <Osztalyfonok ofID="3" osztalyRef="2" tanarRef="2"/>


  <!--Tantárgyak és tankönyvek-->

  <Tantargy targyID="1">
    <nev>Magyar nyelv és irodalom</nev>
  </Tantargy>

  <Tankonyv TkonyvID="1">
    <cim>Az elveszett idő nyomában</cim>
    <iro>József Attila</iro>
    <kiado>Könyvkiadó Kft.</kiado>
    <kiadido>2022-09-01</kiadido>
  </Tankonyv>

  <Konyv TkonyvRef="1" konyvID="1" targyRef="1"> </Konyv>

  <Tantargy targyID="2">
    <nev>Matematika</nev>
  </Tantargy>

  <Tankonyv TkonyvID="2">
    <cim>Az algebrától a geometriáig</cim>
    <iro>Kovács István</iro>
    <kiado>Matektudás Kiadó</kiado>
    <kiadido>2023-03-15</kiadido>
  </Tankonyv>

  <Konyv TkonyvRef="2" konyvID="2" targyRef="2"> </Konyv>

  <Tantargy targyID="3">
    <nev>Biológia</nev>
  </Tantargy>

  <Tankonyv TkonyvID="3">
    <cim>Az élővilág csodái</cim>
    <iro>Nagy Éva</iro>
    <kiado>Biokutató Könyvkiadó</kiado>
    <kiadido>2023-05-20</kiadido>
  </Tankonyv>

  <Konyv TkonyvRef="3" konyvID="3" targyRef="3"> </Konyv>

  <Tantargy targyID="4">
    <nev>Történelem</nev>
  </Tantargy>

  <Tankonyv TkonyvID="4">
    <cim>Az emberiség története</cim>
    <iro>Kiss Gábor</iro>
    <kiado>Történelem Mester Kiadó</kiado>
    <kiadido>2023-07-10</kiadido>
  </Tankonyv>

  <Konyv TkonyvRef="4" konyvID="4" targyRef="4"> </Konyv>

  <Tantargy targyID="5">
    <nev>Fizika</nev>
  </Tantargy>

  <Tankonyv TkonyvID="5">
    <cim>Az erők és mozgás törvényei</cim>
    <iro>Varga János</iro>
    <kiado>Fizika Guru Kiadó</kiado>
    <kiadido>2023-08-25</kiadido>
  </Tankonyv>

  <Konyv TkonyvRef="5" konyvID="5" targyRef="5"> </Konyv>

</Iskola_ZF440N>
